const LEVELS_PER_TEDDY=5,STORAGE_KEY='toxic-teddies-arrow-escape:face-maze-v3',CELL=50,NS='http://www.w3.org/2000/svg';
const TEDDIES=[['tt01','Toxic Toby','Radioactive Ricky','#b9ef2d'],['tt02','Moldy Molly','Fungus Faye','#9ed33e'],['tt03','Dumpster Danny','Trashcan Travis','#d2a64f'],['tt04','Sludge Sam','Gooey Grant','#8ac848'],['tt05','Battery Barry','Leaking Leon','#f0d54f'],['tt06','Maggot Mitch','Wormy Walt','#a6dc52'],['tt07','Burger Bear','Greasy Gina','#d59043'],['tt08','Rusty Randy','Corroded Cory','#cf7c40'],['tt09','Acid Andy','Meltdown Mel','#c2f93f'],['tt10','Gas Mask Max','Fumey Frank','#95c85b'],['tt11','Patchwork Pat','Quilted Quinn','#ce5a8f'],['tt12','Plague Bear','Sickly Sonny','#82bf3a']].map(([id,primary,alternate,accent])=>({id,primary,alternate,accent}));
const LEVELS=[{name:'EASY',size:15,minLen:3,maxLen:7},{name:'GROSS',size:17,minLen:4,maxLen:8},{name:'TOXIC',size:19,minLen:4,maxLen:9},{name:'VILE',size:21,minLen:5,maxLen:10},{name:'LEGENDARY',size:23,minLen:5,maxLen:11}];
const DIRS={up:{dr:-1,dc:0,dx:0,dy:-1},right:{dr:0,dc:1,dx:1,dy:0},down:{dr:1,dc:0,dx:0,dy:1},left:{dr:0,dc:-1,dx:-1,dy:0}},DIR_NAMES=Object.keys(DIRS);
const els=Object.fromEntries(['homeView','gameView','teddyGrid','collectionCounter','backButton','levelTitle','characterName','lives','clearProgress','percentProgress','board','featureLayer','pieceLayer','previewLayer','statusText','resetButton','hintButton','levelButtons','completionModal','completionTitle','completionCopy','replayButton','nextButton','gameOverModal','tryAgainButton'].map(id=>[id,document.getElementById(id)]));
const state={teddyIndex:0,level:1,puzzle:null,lives:3,transitionLock:false,pressTimer:null,longPressTriggered:false,previewTimer:null,save:loadSave(),rng:Math.random};
function loadSave(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{completed:{}}}catch{return{completed:{}}}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.save));updateCollectionCounter()}
function levelKey(id,l){return`${id}-l${l}`}function completed(id,l){return!!state.save.completed[levelKey(id,l)]}function unlocked(id,l){return l===1||completed(id,l-1)}function currentTeddy(){return TEDDIES[state.teddyIndex]}function currentLevel(){return LEVELS[state.level-1]}function cellKey(r,c){return`${r}:${c}`}function parseKey(k){const[r,c]=k.split(':').map(Number);return{row:r,col:c}}
function boot(){bindEvents();renderHome();updateCollectionCounter();const p=new URLSearchParams(location.search),id=p.get('teddy'),l=Number(p.get('level')),i=TEDDIES.findIndex(t=>t.id===id);if(i>=0)openGame(i,Number.isInteger(l)&&l>=1&&l<=5?l:1)}
function bindEvents(){els.backButton.onclick=showHome;els.resetButton.onclick=resetLevel;els.hintButton.onclick=showHint;els.replayButton.onclick=()=>{hideModals();resetLevel()};els.nextButton.onclick=goNext;els.tryAgainButton.onclick=()=>{hideModals();resetLevel()};window.onblur=clearPressTimer}
function renderHome(){els.teddyGrid.innerHTML='';TEDDIES.forEach((t,i)=>{const done=Array.from({length:5},(_,n)=>completed(t.id,n+1)).filter(Boolean).length,b=document.createElement('button');b.className='teddy-card';b.type='button';b.style.setProperty('--card-accent',t.accent);b.innerHTML=`<div class="teddy-card-art"><span class="mini-face"></span></div><div><h3>${t.primary}</h3><p>${t.alternate}</p><strong>${done}/5</strong></div>`;b.onclick=()=>openGame(i,latestUnlocked(t));els.teddyGrid.append(b)})}
function latestUnlocked(t){let x=1;for(let l=1;l<=5;l++)if(unlocked(t.id,l))x=l;return x}function updateCollectionCounter(){els.collectionCounter.textContent=`${Object.keys(state.save.completed).length} / 60`}
function showHome(){clearPreview();clearPressTimer();hideModals();els.gameView.classList.add('hidden');els.homeView.classList.remove('hidden');history.replaceState({},'',location.pathname);renderHome()}
function openGame(i,l){state.teddyIndex=i;state.level=l;els.homeView.classList.add('hidden');els.gameView.classList.remove('hidden');const u=new URL(location.href);u.searchParams.set('teddy',currentTeddy().id);u.searchParams.set('level',String(l));history.replaceState({},'',u);buildLevel()}
function buildLevel(){const t=currentTeddy(),cfg=currentLevel();state.lives=3;state.transitionLock=false;state.rng=mulberry32(hashString(`${t.id}:${state.level}`));state.puzzle=generatePuzzle(cfg.size,cfg.minLen,cfg.maxLen);els.levelTitle.textContent=`Level ${state.level}`;els.characterName.textContent=t.primary;document.documentElement.style.setProperty('--toxic',t.accent);renderLives();renderLevelButtons();renderBoard();updateProgress();setStatus(`${cfg.name} · clear the open arrow paths`)}
function resetLevel(){clearPreview();clearPressTimer();hideModals();buildLevel()}
function renderLevelButtons(){els.levelButtons.innerHTML='';const t=currentTeddy();for(let l=1;l<=5;l++){const b=document.createElement('button');b.textContent=l;b.className='level-chip';if(l===state.level)b.classList.add('active');if(completed(t.id,l))b.classList.add('done');if(!unlocked(t.id,l))b.disabled=true;b.onclick=()=>openGame(state.teddyIndex,l);els.levelButtons.append(b)}}
function renderLives(){els.lives.innerHTML='';for(let i=0;i<3;i++){const d=document.createElement('span');d.className=`life-drop${i>=state.lives?' lost':''}`;els.lives.append(d)}}
function renderBoard(){const px=state.puzzle.size*CELL;els.board.setAttribute('viewBox',`0 0 ${px} ${px}`);els.previewLayer.setAttribute('viewBox',`0 0 ${px} ${px}`);els.featureLayer.innerHTML='';els.pieceLayer.innerHTML='';els.previewLayer.innerHTML='';els.featureLayer.append(createDefs());els.featureLayer.append(renderFeatures(state.puzzle.size,currentTeddy()));state.puzzle.pieces.forEach(p=>{const g=document.createElementNS(NS,'g');g.classList.add('path-piece',`piece-${p.variant}`);g.dataset.id=p.id;const points=p.cells.map(({row,col})=>`${col*CELL+CELL/2},${row*CELL+CELL/2}`).join(' '),shadow=document.createElementNS(NS,'polyline'),line=document.createElementNS(NS,'polyline'),hit=document.createElementNS(NS,'polyline');shadow.setAttribute('points',points);shadow.setAttribute('class','piece-shadow');line.setAttribute('points',points);line.setAttribute('class','piece-line');hit.setAttribute('points',points);hit.setAttribute('class','piece-hit');g.append(shadow,line,hit);g.addEventListener('pointerdown',e=>beginLongPress(e,p));g.addEventListener('pointerup',endLongPress);g.addEventListener('pointercancel',endLongPress);g.addEventListener('pointerleave',cancelLongPress);g.addEventListener('click',e=>{e.preventDefault();if(state.longPressTriggered){state.longPressTriggered=false;return}attemptMove(p)});p.element=g;els.pieceLayer.append(g)})}
function createDefs(){const d=document.createElementNS(NS,'defs');d.innerHTML=`<filter id="toxicGlow" x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><marker id="pieceArrowToxic" viewBox="0 0 16 16" refX="13" refY="8" markerWidth="7" markerHeight="7" orient="auto"><path d="M1 1L14 8L1 15" fill="none" stroke="#b7ec2e" stroke-width="2.7" stroke-linecap="round" stroke-linejoin="round"/></marker><marker id="pieceArrowStitch" viewBox="0 0 16 16" refX="13" refY="8" markerWidth="7" markerHeight="7" orient="auto"><path d="M1 1L14 8L1 15" fill="none" stroke="#9b5427" stroke-width="2.7" stroke-linecap="round" stroke-linejoin="round"/></marker><marker id="pieceArrowRust" viewBox="0 0 16 16" refX="13" refY="8" markerWidth="7" markerHeight="7" orient="auto"><path d="M1 1L14 8L1 15" fill="none" stroke="#d17a36" stroke-width="2.7" stroke-linecap="round" stroke-linejoin="round"/></marker>`;return d}
function renderFeatures(size,t){const w=size*CELL,h=w,cx=w/2,cy=h*.54,rx=w*.37,ry=h*.39,ey=cy-ry*.24,eo=rx*.56,er=w*.074,ery=h*.16,erx=w*.16,earY=cy-ry*.88,earO=rx*.82,mY=cy+ry*.45,g=document.createElementNS(NS,'g');g.innerHTML=`<ellipse class="face-outline" cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}"/><ellipse class="face-outline" cx="${cx-earO}" cy="${earY}" rx="${erx}" ry="${ery}"/><ellipse class="face-outline" cx="${cx+earO}" cy="${earY}" rx="${erx}" ry="${ery}"/><path class="drip" d="M${cx-rx*.98} ${cy-ry*.55}Q${cx-rx*1.05} ${cy-ry*.38} ${cx-rx*1.04} ${cy-ry*.18}"/><path class="drip" d="M${cx-rx*.86} ${cy+ry*.54}Q${cx-rx*.86} ${cy+ry*.81} ${cx-rx*.87} ${cy+ry*.98}"/><path class="drip" d="M${cx+rx*.12} ${cy+ry*.78}Q${cx+rx*.15} ${cy+ry*.94} ${cx+rx*.16} ${cy+ry*1.07}"/><path class="drip" d="M${cx+rx*.92} ${cy+ry*.53}Q${cx+rx*.95} ${cy+ry*.75} ${cx+rx*.96} ${cy+ry*.98}"/><g class="center-seam"><path d="M${cx} ${cy-ry*.88}V${cy+ry*.12}"/>${Array.from({length:8},(_,i)=>{const y=cy-ry*.72+i*ry*.12;return`<path class="seam-stitch" d="M${cx-w*.03} ${y}H${cx+w*.03}"/>`}).join('')}</g><g class="button-eye"><circle cx="${cx-eo}" cy="${ey}" r="${er}"/><path d="M${cx-eo-er*.35} ${ey-er*.35}L${cx-eo+er*.35} ${ey+er*.35}M${cx-eo+er*.35} ${ey-er*.35}L${cx-eo-er*.35} ${ey+er*.35}"/></g><g class="infected-eye"><circle class="eye-white" cx="${cx+eo}" cy="${ey}" r="${er}"/><circle class="iris" cx="${cx+eo}" cy="${ey}" r="${er*.46}" fill="${t.accent}"/><circle class="pupil" cx="${cx+eo}" cy="${ey}" r="${er*.16}"/><path class="drip" d="M${cx+eo-er*.42} ${ey+er*.66}Q${cx+eo-er*.38} ${ey+er*1.06} ${cx+eo-er*.31} ${ey+er*.66}M${cx+eo+er*.18} ${ey+er*.74}Q${cx+eo+er*.22} ${ey+er*1.18} ${cx+eo+er*.26} ${ey+er*.76}"/></g><g class="nose"><ellipse cx="${cx}" cy="${cy+ry*.05}" rx="${rx*.18}" ry="${ry*.10}"/><path d="M${cx-rx*.07} ${cy+ry*.05}Q${cx} ${cy+ry*.10} ${cx+rx*.07} ${cy+ry*.05}"/></g><g><path class="mouth-bg" d="M${cx-rx*.34} ${mY-ry*.02}Q${cx} ${mY+ry*.20} ${cx+rx*.34} ${mY-ry*.02}Q${cx} ${mY+ry*.09} ${cx-rx*.34} ${mY-ry*.02}Z"/>${Array.from({length:9},(_,i)=>{const x=cx-rx*.28+i*rx*.072,y=mY+(i%2===0?-ry*.01:ry*.02);return`<rect class="tooth" x="${x}" y="${y}" width="${rx*.055}" height="${ry*.11}" rx="${rx*.008}"/>`}).join('')}</g><g><path class="cheek-patch" d="M${cx-rx*.92} ${cy+ry*.08}L${cx-rx*.66} ${cy-ry*.02}L${cx-rx*.61} ${cy+ry*.25}L${cx-rx*.87} ${cy+ry*.34}Z"/>${Array.from({length:5},(_,i)=>{const x=cx-rx*.89+i*rx*.055,y=cy+ry*.13+i*3;return`<path class="cheek-stitch" d="M${x} ${y}l${rx*.01} ${ry*.10}"/>`}).join('')}</g>${Array.from({length:4},(_,i)=>{const x=cx-earO-rx*.02+i*rx*.06,y=earY-ery*.18+i*ry*.03;return`<path class="ear-stitch" d="M${x} ${y}l${rx*.03} ${ry*.07}"/>`}).join('')}${Array.from({length:4},(_,i)=>{const x=cx+earO-rx*.12+i*rx*.06,y=earY-ery*.22+i*ry*.03;return`<path class="ear-stitch" d="M${x} ${y}l${rx*.03} ${ry*.07}"/>`}).join('')}`;return g}
function generatePuzzle(size,minLen,maxLen){const mask=makeFaceMask(size),keys=[...mask].sort(),occupied=new Set(),pieces=[];let id=1,guard=0;while(occupied.size<mask.size&&guard++<5000){const remaining=keys.filter(k=>!occupied.has(k)),exits=[];for(const k of remaining){const{row,col}=parseKey(k);for(const dirName of DIR_NAMES)if(clearRay(row,col,dirName,size,occupied))exits.push({key:k,row,col,dirName})}if(!exits.length)break;const exit=pickRandom(exits,state.rng),path=buildPathFromExit(exit,remaining.length,minLen,maxLen,size,mask,occupied);if(!path.length)continue;path.forEach(c=>occupied.add(cellKey(c.row,c.col)));pieces.push({id:`p${id++}`,cells:path,exitDir:exit.dirName,variant:classifyVariant(path,size),element:null,removed:false})}for(const k of keys.filter(k=>!occupied.has(k))){const{row,col}=parseKey(k),dirName=DIR_NAMES.find(d=>clearRay(row,col,d,size,occupied))||'up',path=[{row,col}];occupied.add(k);pieces.push({id:`p${id++}`,cells:path,exitDir:dirName,variant:classifyVariant(path,size),element:null,removed:false})}pieces.reverse();return{size,mask,pieces,active:new Set(pieces.map(p=>p.id)),cleared:0}}
function makeFaceMask(size){const mask=new Set(),half=(size-1)/2;for(let row=0;row<size;row++)for(let col=0;col<size;col++){const x=(col-half)/half,y=(row-half)/half,head=x*x/(.70*.70)+(y-.05)*(y-.05)/(.76*.76)<=1,left=(x+.66)**2/(.25**2)+(y+.64)**2/(.25**2)<=1,right=(x-.66)**2/(.25**2)+(y+.64)**2/(.25**2)<=1;if(!(head||left||right))continue;const le=(x+.28)**2/(.11**2)+(y+.14)**2/(.11**2)<=1,re=(x-.28)**2/(.11**2)+(y+.14)**2/(.11**2)<=1,n=x*x/(.12**2)+(y-.02)*(y-.02)/(.08**2)<=1,m=x*x/(.34**2)+(y-.45)*(y-.45)/(.15**2)<=1&&y>.31,p=(x+.52)**2/(.13**2)+(y-.12)**2/(.13**2)<=1;if(!(le||re||n||m||p))mask.add(cellKey(row,col))}return mask}
function clearRay(row,col,dirName,size,occupied){const d=DIRS[dirName];for(let r=row+d.dr,c=col+d.dc;r>=0&&r<size&&c>=0&&c<size;r+=d.dr,c+=d.dc)if(occupied.has(cellKey(r,c)))return false;return true}
function buildPathFromExit(exit,target,minLen,maxLen,size,mask,occupied){const desired=clamp(randomInt(minLen,maxLen,state.rng),1,target),inv=opposite(exit.dirName),sr=exit.row+DIRS[inv].dr,sc=exit.col+DIRS[inv].dc,path=[{row:exit.row,col:exit.col}],seen=new Set([exit.key]);let cur={row:exit.row,col:exit.col};while(path.length<desired){const options=neighbors(cur.row,cur.col,size).filter(n=>mask.has(cellKey(n.row,n.col))&&!occupied.has(cellKey(n.row,n.col))&&!seen.has(cellKey(n.row,n.col))&&!(path.length===1&&n.row===sr&&n.col===sc));if(!options.length)break;options.sort((a,b)=>scoreCell(b,size)-scoreCell(a,size));const chosen=pickRandom(options.slice(0,Math.min(3,options.length)),state.rng);path.push(chosen);seen.add(cellKey(chosen.row,chosen.col));cur=chosen}if(path.length<2&&mask.has(cellKey(sr,sc))&&!occupied.has(cellKey(sr,sc)))path.push({row:sr,col:sc});return path.reverse()}
function scoreCell(c,size){const h=(size-1)/2,x=Math.abs((c.col-h)/h),y=Math.abs((c.row-h)/h);return 1-(x*.65+y*.35)+state.rng()*.12}function neighbors(r,c,size){return DIR_NAMES.map(name=>({row:r+DIRS[name].dr,col:c+DIRS[name].dc})).filter(n=>n.row>=0&&n.row<size&&n.col>=0&&n.col<size)}
function classifyVariant(path,size){const ar=path.reduce((s,c)=>s+c.row,0)/path.length,ac=path.reduce((s,c)=>s+c.col,0)/path.length,c=(size-1)/2;if(Math.abs(ac-c)<size*.07&&ar<size*.55)return'stitch';if(ac<size*.28&&ar>size*.46&&ar<size*.70)return'rust';if(ar<size*.23&&(ac<size*.26||ac>size*.74))return'stitch';return'toxic'}
function beginLongPress(e,p){if(state.transitionLock||p.removed)return;clearPressTimer();state.longPressTriggered=false;state.pressTimer=setTimeout(()=>{state.longPressTriggered=true;inspectPiece(p)},340);e.currentTarget.setPointerCapture?.(e.pointerId)}function clearPressTimer(){if(state.pressTimer)clearTimeout(state.pressTimer);state.pressTimer=null}function endLongPress(){clearPressTimer()}function cancelLongPress(){clearPressTimer()}
function inspectPiece(p){clearPreview();p.element?.classList.add('inspecting');const x=previewRay(p);if(!x.blockers.length)setStatus('Open exit · this path can slide out now');else{setStatus(`Blocked · ${x.blockers.length} path${x.blockers.length>1?'s':''} ahead`);x.blockers.forEach(b=>b.element?.classList.add('blocking'))}state.previewTimer=setTimeout(clearPreview,1200)}
function clearPreview(){if(state.previewTimer)clearTimeout(state.previewTimer);state.previewTimer=null;els.previewLayer.innerHTML='';state.puzzle?.pieces.forEach(p=>p.element?.classList.remove('inspecting','hinting','blocking','blocked-bump'))}
function previewRay(p){const d=DIRS[p.exitDir],e=p.cells[p.cells.length-1],sx=e.col*CELL+CELL/2,sy=e.row*CELL+CELL/2;let x=sx,y=sy,r=e.row+d.dr,c=e.col+d.dc;const blockers=[];while(r>=0&&r<state.puzzle.size&&c>=0&&c<state.puzzle.size){x=c*CELL+CELL/2;y=r*CELL+CELL/2;const b=pieceAt(r,c);if(b&&!blockers.includes(b))blockers.push(b);r+=d.dr;c+=d.dc}const line=document.createElementNS(NS,'line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',x+d.dx*CELL/2);line.setAttribute('y2',y+d.dy*CELL/2);line.setAttribute('class',`preview-ray${blockers.length?' blocked':''}`);els.previewLayer.append(line);return{blockers}}
function pieceAt(r,c){for(const p of state.puzzle.pieces)if(!p.removed&&p.cells.some(x=>x.row===r&&x.col===c))return p;return null}
function blockersAhead(p){const d=DIRS[p.exitDir],e=p.cells[p.cells.length-1],out=[];for(let r=e.row+d.dr,c=e.col+d.dc;r>=0&&r<state.puzzle.size&&c>=0&&c<state.puzzle.size;r+=d.dr,c+=d.dc){const b=pieceAt(r,c);if(b&&b.id!==p.id&&!out.includes(b))out.push(b)}return out}
function attemptMove(p){if(state.transitionLock||p.removed)return;clearPreview();const b=blockersAhead(p);if(b.length){bumpBlocked(p,b[0]);return}movePieceOut(p)}
function bumpBlocked(p,b){state.lives=Math.max(0,state.lives-1);renderLives();p.element?.classList.add('blocked-bump');b.element?.classList.add('blocking');setTimeout(()=>{p.element?.classList.remove('blocked-bump');b.element?.classList.remove('blocking')},420);setStatus('Blocked · clear the first path in that direction');if(state.lives===0)setTimeout(()=>els.gameOverModal.classList.remove('hidden'),250)}
function movePieceOut(p){state.transitionLock=true;const d=DIRS[p.exitDir],dist=state.puzzle.size*CELL*1.15;p.element?.style.setProperty('--exit-x',`${d.dx*dist}px`);p.element?.style.setProperty('--exit-y',`${d.dy*dist}px`);p.element?.classList.add('exiting');setStatus('Lane cleared · new exits may be open');setTimeout(()=>{p.removed=true;p.element?.classList.add('removed');state.puzzle.active.delete(p.id);state.puzzle.cleared++;state.transitionLock=false;updateProgress();if(!state.puzzle.active.size)completeLevel()},280)}
function showHint(){clearPreview();const open=state.puzzle.pieces.filter(p=>!p.removed&&!blockersAhead(p).length);if(!open.length)return;const p=pickRandom(open,state.rng);p.element?.classList.add('hinting');previewRay(p);setStatus('Hint · that path can leave now');state.previewTimer=setTimeout(clearPreview,1200)}
function updateProgress(){const total=state.puzzle.pieces.length,cleared=state.puzzle.cleared;els.clearProgress.textContent=`${cleared} / ${total}`;els.percentProgress.textContent=`${Math.round(cleared/total*100)}%`}
function completeLevel(){const t=currentTeddy();state.save.completed[levelKey(t.id,state.level)]=true;persist();els.completionTitle.textContent=`${t.primary} · Level ${state.level}`;els.completionCopy.textContent=state.level===5?`You cleared all five ${t.primary} boards.`:`Level ${state.level+1} is unlocked.`;els.completionModal.classList.remove('hidden');renderLevelButtons()}
function goNext(){hideModals();if(state.level<5)openGame(state.teddyIndex,state.level+1);else showHome()}function hideModals(){els.completionModal.classList.add('hidden');els.gameOverModal.classList.add('hidden')}function setStatus(t){els.statusText.textContent=t}
function pickRandom(a,r=Math.random){return a[Math.floor(r()*a.length)]}function randomInt(min,max,r=Math.random){return Math.floor(r()*(max-min+1))+min}function clamp(v,min,max){return Math.min(max,Math.max(min,v))}function opposite(d){return d==='up'?'down':d==='down'?'up':d==='left'?'right':'left'}function hashString(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
boot();